create or replace PROCEDURE sp_collapse_duplicate_cart_items IS
BEGIN
  MERGE INTO SHOPPINGCART sc
  USING (
    SELECT USERID, VARIATIONID, SUM(QUANTITY) AS TOTAL_QTY
    FROM SHOPPINGCART
    GROUP BY USERID, VARIATIONID
    HAVING COUNT(*) > 1
  ) dup
  ON (sc.USERID = dup.USERID AND sc.VARIATIONID = dup.VARIATIONID)
  WHEN MATCHED THEN
    UPDATE SET sc.QUANTITY = dup.TOTAL_QTY;

  DELETE FROM SHOPPINGCART sc
  WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM SHOPPINGCART
    GROUP BY USERID, VARIATIONID
  );

  DBMS_OUTPUT.PUT_LINE('Duplicate cart entries collapsed successfully.');
END;
