-- 01_CreatedAt_and_UpdatedAt_Triggers_For_Users.sql
-- This script creates BEFORE INSERT and BEFORE INSERT OR UPDATE triggers to auto-set CREATEDAT and UPDATEDAT timestamps on the USERS table.

CREATE OR REPLACE TRIGGER TRG_USERS_CreatedAt
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  :NEW.CREATEDAT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_USERS_UpdatedAt
BEFORE INSERT OR UPDATE ON USERS
FOR EACH ROW
BEGIN
  :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
END;
/
