-- 02_CreatedAt_and_UpdatedAt_Triggers_For_Usertiers.sql
-- This script creates BEFORE INSERT and BEFORE INSERT OR UPDATE triggers to auto-set CREATEDAT and UPDATEDAT timestamps on the USERTIERS table.

CREATE OR REPLACE TRIGGER TRG_USERTIERS_CreatedAt
BEFORE INSERT ON USERTIERS
FOR EACH ROW
BEGIN
  :NEW.CREATEDAT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_USERTIERS_UpdatedAt
BEFORE INSERT OR UPDATE ON USERTIERS
FOR EACH ROW
BEGIN
  :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
END;
/
