-- 03_CreatedAt_and_UpdatedAt_Triggers_For_Products.sql
-- This script creates BEFORE INSERT and BEFORE INSERT OR UPDATE triggers to auto-set CREATEDAT and UPDATEDAT timestamps on the PRODUCTS table.

CREATE OR REPLACE TRIGGER TRG_PRODUCTS_CreatedAt
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
BEGIN
  :NEW.CREATEDAT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTS_UpdatedAt
BEFORE INSERT OR UPDATE ON PRODUCTS
FOR EACH ROW
BEGIN
  :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
END;
/
