-- 04_CreatedAt_and_UpdatedAt_Triggers_For_Productvariations.sql
-- This script creates BEFORE INSERT and BEFORE INSERT OR UPDATE triggers to auto-set CREATEDAT and UPDATEDAT timestamps on the PRODUCTVARIATIONS table.

CREATE OR REPLACE TRIGGER TRG_PRODUCTVARIATIONS_CreatedAt
BEFORE INSERT ON PRODUCTVARIATIONS
FOR EACH ROW
BEGIN
  :NEW.CREATEDAT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTVARIATIONS_UpdatedAt
BEFORE INSERT OR UPDATE ON PRODUCTVARIATIONS
FOR EACH ROW
BEGIN
  :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
END;
/
