-- 05_CreatedAt_and_UpdatedAt_Triggers_For_Productimages.sql
-- This script creates BEFORE INSERT and BEFORE INSERT OR UPDATE triggers to auto-set CREATEDAT and UPDATEDAT timestamps on the PRODUCTIMAGES table.

CREATE OR REPLACE TRIGGER TRG_PRODUCTIMAGES_CreatedAt
BEFORE INSERT ON PRODUCTIMAGES
FOR EACH ROW
BEGIN
  :NEW.CREATEDAT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTIMAGES_UpdatedAt
BEFORE INSERT OR UPDATE ON PRODUCTIMAGES
FOR EACH ROW
BEGIN
  :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
END;
/
