-- 06_CreatedAt_and_UpdatedAt_Triggers_For_Sizeoptions.sql
-- This script creates BEFORE INSERT and BEFORE INSERT OR UPDATE triggers to auto-set CREATEDAT and UPDATEDAT timestamps on the SIZEOPTIONS table.

CREATE OR REPLACE TRIGGER TRG_SIZEOPTIONS_CreatedAt
BEFORE INSERT ON SIZEOPTIONS
FOR EACH ROW
BEGIN
  :NEW.CREATEDAT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SIZEOPTIONS_UpdatedAt
BEFORE INSERT OR UPDATE ON SIZEOPTIONS
FOR EACH ROW
BEGIN
  :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
END;
/
