-- 07_CreatedAt_and_UpdatedAt_Triggers_For_Orders.sql
-- This script creates BEFORE INSERT and BEFORE INSERT OR UPDATE triggers to auto-set CREATEDAT and UPDATEDAT timestamps on the ORDERS table.

CREATE OR REPLACE TRIGGER TRG_ORDERS_CreatedAt
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
  :NEW.CREATEDAT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_ORDERS_UpdatedAt
BEFORE INSERT OR UPDATE ON ORDERS
FOR EACH ROW
BEGIN
  :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
END;
/
