-- 10_CreatedAt_and_UpdatedAt_Triggers_For_Shoppingcart.sql
-- This script creates BEFORE INSERT and BEFORE INSERT OR UPDATE triggers to auto-set CREATEDAT and UPDATEDAT timestamps on the SHOPPINGCART table.

CREATE OR REPLACE TRIGGER TRG_SHOPPINGCART_CreatedAt
BEFORE INSERT ON SHOPPINGCART
FOR EACH ROW
BEGIN
  :NEW.CREATEDAT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SHOPPINGCART_UpdatedAt
BEFORE INSERT OR UPDATE ON SHOPPINGCART
FOR EACH ROW
BEGIN
  :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
END;
/
