-- 11_CreatedAt_and_UpdatedAt_Triggers_For_Reviews.sql
-- This script creates BEFORE INSERT and BEFORE INSERT OR UPDATE triggers to auto-set CREATEDAT and UPDATEDAT timestamps on the REVIEWS table.

CREATE OR REPLACE TRIGGER TRG_REVIEWS_CreatedAt
BEFORE INSERT ON REVIEWS
FOR EACH ROW
BEGIN
  :NEW.CREATEDAT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_REVIEWS_UpdatedAt
BEFORE INSERT OR UPDATE ON REVIEWS
FOR EACH ROW
BEGIN
  :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
END;
/
