-- 13_CreatedAt_and_UpdatedAt_Triggers_For_Productattributes.sql
-- This script creates BEFORE INSERT and BEFORE INSERT OR UPDATE triggers to auto-set CREATEDAT and UPDATEDAT timestamps on the PRODUCTATTRIBUTES table.

CREATE OR REPLACE TRIGGER TRG_PRODUCTATTRIBUTES_CreatedAt
BEFORE INSERT ON PRODUCTATTRIBUTES
FOR EACH ROW
BEGIN
  :NEW.CREATEDAT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTATTRIBUTES_UpdatedAt
BEFORE INSERT OR UPDATE ON PRODUCTATTRIBUTES
FOR EACH ROW
BEGIN
  :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
END;
/
