-- 15_CreatedAt_and_UpdatedAt_Triggers_For_Productattributemapping.sql
-- This script creates BEFORE INSERT and BEFORE INSERT OR UPDATE triggers to auto-set CREATEDAT and UPDATEDAT timestamps on the PRODUCTATTRIBUTEMAPPING table.

CREATE OR REPLACE TRIGGER TRG_PRODUCTATTRIBUTEMAPPING_CreatedAt
BEFORE INSERT ON PRODUCTATTRIBUTEMAPPING
FOR EACH ROW
BEGIN
  :NEW.CREATEDAT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTATTRIBUTEMAPPING_UpdatedAt
BEFORE INSERT OR UPDATE ON PRODUCTATTRIBUTEMAPPING
FOR EACH ROW
BEGIN
  :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
END;
/
