-- 16_CreatedAt_and_UpdatedAt_Triggers_For_Productcategories.sql
-- This script creates BEFORE INSERT and BEFORE INSERT OR UPDATE triggers to auto-set CREATEDAT and UPDATEDAT timestamps on the PRODUCTCATEGORIES table.

CREATE OR REPLACE TRIGGER TRG_PRODUCTCATEGORIES_CreatedAt
BEFORE INSERT ON PRODUCTCATEGORIES
FOR EACH ROW
BEGIN
  :NEW.CREATEDAT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTCATEGORIES_UpdatedAt
BEFORE INSERT OR UPDATE ON PRODUCTCATEGORIES
FOR EACH ROW
BEGIN
  :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
END;
/
