-- 17_CreatedAt_and_UpdatedAt_Triggers_For_Colors.sql
-- This script creates BEFORE INSERT and BEFORE INSERT OR UPDATE triggers to auto-set CREATEDAT and UPDATEDAT timestamps on the COLORS table.

CREATE OR REPLACE TRIGGER TRG_COLORS_CreatedAt
BEFORE INSERT ON COLORS
FOR EACH ROW
BEGIN
  :NEW.CREATEDAT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_COLORS_UpdatedAt
BEFORE INSERT OR UPDATE ON COLORS
FOR EACH ROW
BEGIN
  :NEW.UPDATEDAT := CURRENT_TIMESTAMP;
END;
/
