-- 19_Update_Stock_On_Order.sql
-- This trigger deducts stock from PRODUCTVARIATIONS after an ORDERLINEITEM is inserted.

CREATE OR REPLACE TRIGGER "ERETAILER_DBA"."TRG_UpdateStockOnOrder"
AFTER INSERT ON "ERETAILER_DBA"."ORDERLINEITEMS"
FOR EACH ROW
BEGIN
    UPDATE "ERETAILER_DBA"."PRODUCTVARIATIONS"
    SET STOCKQUANTITY = STOCKQUANTITY - :NEW.QUANTITY
    WHERE VARIATIONID = :NEW.VARIATIONID;
END;
/


