-- 20_Collapse_Duplicate_Cart_Entries.sql
-- This trigger merges quantity if a duplicate USERID + VARIATIONID entry exists in SHOPPINGCART.

CREATE OR REPLACE TRIGGER TRG_CollapseDuplicateCartEntries
BEFORE INSERT ON SHOPPINGCART
FOR EACH ROW
DECLARE
    v_existing_qty SHOPPINGCART.QUANTITY%TYPE;
BEGIN
    SELECT QUANTITY
    INTO v_existing_qty
    FROM SHOPPINGCART
    WHERE USERID = :NEW.USERID AND VARIATIONID = :NEW.VARIATIONID
    FOR UPDATE;

    UPDATE SHOPPINGCART
    SET QUANTITY = QUANTITY + :NEW.QUANTITY
    WHERE USERID = :NEW.USERID AND VARIATIONID = :NEW.VARIATIONID;

    :NEW.QUANTITY := NULL;
    RAISE_APPLICATION_ERROR(-20001, 'Duplicate entry merged. Insert skipped.');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
END;
/



