-- Cleanup_All_Tables_Delete_Cascade.sql
-- Purpose: Deletes all rows from all tables by manually cascading deletes in FK-safe order

BEGIN
    -- Delete child records first
    DELETE FROM "ERETAILER_DBA"."ORDERLINEITEMS";
    DELETE FROM "ERETAILER_DBA"."ORDERS";
    DELETE FROM "ERETAILER_DBA"."SHOPPINGCART";
    DELETE FROM "ERETAILER_DBA"."REVIEWS";
    DELETE FROM "ERETAILER_DBA"."PRODUCTIMAGES";
    DELETE FROM "ERETAILER_DBA"."PRODUCTATTRIBUTEMAPPING";
    DELETE FROM "ERETAILER_DBA"."PRODUCTATTRIBUTEVALUES";
    DELETE FROM "ERETAILER_DBA"."PRODUCTATTRIBUTES";
    DELETE FROM "ERETAILER_DBA"."PRODUCTVARIATIONS";
    DELETE FROM "ERETAILER_DBA"."PRODUCTS";
    DELETE FROM "ERETAILER_DBA"."PRODUCTCATEGORIES";

    DELETE FROM "ERETAILER_DBA"."BRANDS";
    DELETE FROM "ERETAILER_DBA"."COLORS";
    DELETE FROM "ERETAILER_DBA"."SIZEOPTIONS";
    DELETE FROM "ERETAILER_DBA"."ADDRESS";
    DELETE FROM "ERETAILER_DBA"."USERS";
    DELETE FROM "ERETAILER_DBA"."USERTIERS";

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('All tables deleted in FK-safe cascade order.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Delete cascade failed: ' || SQLERRM);
END;
/