-- PRODUCTS
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE product_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE product_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

-- PRODUCTVARIATIONS
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE variation_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE variation_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

-- PRODUCTIMAGES
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE productimage_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE productimage_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ORDERS
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE order_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE order_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ORDERLINEITEMS
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE orderline_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE orderline_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

-- SHOPPINGCART
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE cart_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE cart_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

-- REVIEWS
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE review_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE review_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

-- User
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE user_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE user_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Address
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE address_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE address_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
