-- Sequence for PRODUCTS table
CREATE SEQUENCE product_seq
  START WITH 1000
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Sequence for PRODUCTVARIATIONS table
CREATE SEQUENCE variation_seq
  START WITH 1000
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Sequence for PRODUCTIMAGES table
CREATE SEQUENCE productimage_seq
  START WITH 1000
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Sequence for ORDER table
CREATE SEQUENCE order_seq
  START WITH 1000
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Sequence for ORDERLINEITEMS table
CREATE SEQUENCE orderline_seq
  START WITH 1000
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Sequence for SHOPPINGCART table
CREATE SEQUENCE cart_seq
  START WITH 1000
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Sequence for REVIEWS table
CREATE SEQUENCE review_seq
  START WITH 1000
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
